### ISSUE TITLE
Test suite failure

### ISSUE THREAD

**Issue by tillea** [brodie/cram#32]
Hi,
as you can read in the [Debian bug report](https://bugs.debian.org/897516) the test suite fails since some time.

    COVERAGE=python-coverage PYTHON=python PYTHONPATH=`pwd` scripts/cram \
      tests
    ..s...ss...
    # Ran 11 tests, 3 skipped, 0 failed.
    python-coverage report --fail-under=100
    Name                Stmts   Miss  Cover
    ---------------------------------------
    cram/__init__.py        3      0   100%
    cram/__main__.py        6      6     0%
    cram/_cli.py           74      0   100%
    cram/_diff.py          89      0   100%
    cram/_encoding.py      67     32    52%
    cram/_main.py         135      0   100%
    cram/_process.py       14      0   100%
    cram/_run.py           40      0   100%
    cram/_test.py         104      0   100%
    cram/_xunit.py         66      0   100%
    ---------------------------------------
    TOTAL                 598     38    94%
    make[2]: *** [Makefile:35: test] Error 2

I have relaxed the fail-under parameter but now there is another failure which you can read in the [build log](https://buildd.debian.org/status/fetch.php?pkg=cram&arch=all&ver=0.7-2&stamp=1526830338&raw=0) (see at the end):

    COVERAGE=python-coverage PYTHON=python PYTHONPATH=`pwd` scripts/cram \
      tests
    ..s..!
    --- tests/interactive.t
    +++ tests/interactive.t.err
    @@ -277,11 +277,22 @@
          \d (re)
       Accept this change? [yN] y
       patch failed
    -  examples/fail.t: merge failed
    -
    -  # Ran 1 tests, 0 skipped, 1 failed.
    -  [1]
    -  $ md5 examples/fail.t examples/fail.t.err
    -  .*\b0f598c2b7b8ca5bcb8880e492ff6b452\b.* (re)
    -  .*\b7a23dfa85773c77648f619ad0f9df554\b.* (re)
    +  Traceback (most recent call last):
    +    File "/<<PKGBUILDDIR>>/tests/../scripts/cram", line 7, in <module>
    +      sys.exit(cram.main(sys.argv[1:]))
    +    File "/<<PKGBUILDDIR>>/cram/_main.py", line 197, in main
    +      refout, postout, diff = test()
    +    File "/<<PKGBUILDDIR>>/cram/_cli.py", line 121, in testwrapper
    +      if _patch(patchcmd, diff):
    +    File "/<<PKGBUILDDIR>>/cram/_cli.py", line 54, in _patch
    +      out, retcode = execute([cmd, '-p0'], stdin=b('').join(diff))
    +    File "/<<PKGBUILDDIR>>/cram/_process.py", line 53, in execute
    +      out, err = p.communicate(stdin)
    +    File "/usr/lib/python2.7/subprocess.py", line 473, in communicate
    +      self.stdin.close()
    +  IOError: [Errno 32] Broken pipe
    +  [1]
    +  $ md5 examples/fail.t examples/fail.t.err
    +  0f598c2b7b8ca5bcb8880e492ff6b452  examples/fail.t
    +  7a23dfa85773c77648f619ad0f9df554  examples/fail.t.err
       $ rm patch examples/fail.t.err
    ss...
    # Ran 11 tests, 3 skipped, 1 failed.
    make[2]: *** [Makefile:34: test] Error 1

Could you please have a look.
Kind regards, Andreas.

**Comment by tillea** [comment]
Any news for this issue?

**Comment by tillea** [comment]
Are you able to reproduce the issue or do you need further information?

**Comment by tillea** [comment]
There was a further comment in the [Debian bug lop](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=897516#53) that suspects a correlation between this issue and python-coverage >= 4.5.  What is your opinion about this?

**Comment by tillea** [comment]
Could you please confirm that this project is alive and you have realised this issue?
